# Generated by Django 4.2.2 on 2024-01-05 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogPersonal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeloblog',
            name='imagen',
        ),
    ]
