# Generated by Django 4.2.2 on 2024-01-05 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppBlogPersonal', '0002_remove_modeloblog_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeloblog',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
